hmrc/android-components

- components-test/build.gradle
- components-test/src/main/java/uk/gov/hmrc/components/test/molecule/input/TextInputViewActions.kt
> Add clearText espresso action for TextInputView

- CHANGELOG.md
> Update Changelog for 3.6.0

- CHANGELOG.md
- README.md
- components/src/main/java/uk/gov/hmrc/components/organism/information/InformationMessageCardView.kt
- sample/src/main/java/uk/gov/hmrc/components/sample/organisms/InformationMessageCardFragment.kt
Ensure buttons are cleared before adding new ones to prevent duplicate buttons.
> Info message duplicated buttons fix

- CHANGELOG.md
- README.md
- components/src/main/java/uk/gov/hmrc/components/molecule/warning/WarningView.kt
- components/src/main/java/uk/gov/hmrc/components/organism/information/InformationMessageCardView.kt
- components/src/main/res/values/attrs.xml
- sample/src/main/java/uk/gov/hmrc/components/sample/organisms/InformationMessageCardFragment.kt
- sample/src/main/res/layout/fragment_information_message_card.xml
- sample/src/main/res/values/strings.xml
Add ability to update content description for InformationMessageCardView
> Add ability to update content description for InformationMessageCardView

- CHANGELOG.md
> Release 3.11.0

- README.md
https://jira.tools.tax.service.gov.uk/browse/HMA-3872
Updated readme to:
* Document release process in detail
* Explain the different ways of setting environment variables
* Add badge for current release version
No code changes have been made
> HMA-3872 improve components release documentation

- README.md
- fastlane/Fastfile
- release.sh
> task/improve-release-process - invoke release pipeline via API call

- README.md
Documents the extra permissions that are needed for the Github personal access token in order to release.
> Extra permissions need to be granted to the Github personal access token

- CHANGELOG.md
- components/src/main/java/uk/gov/hmrc/components/molecule/input/TextInputView.kt
- sample/build.gradle
- sample/src/main/java/uk/gov/hmrc/components/sample/molecules/TextInputFragment.kt
- sample/src/main/res/layout/fragment_text_input.xml
Improved content description for `TextInputView` to prevent duplicating error announcements when counter is exceeded.
> TextInputView counter errors

- CHANGELOG.md
- build.gradle
- components/build.gradle
- components/src/main/java/uk/gov/hmrc/components/extensions/ContextExt.kt
- components/src/main/java/uk/gov/hmrc/components/extensions/FloatExtensions.kt
- components/src/main/java/uk/gov/hmrc/components/molecule/input/TextInputView.kt
- sample/build.gradle
https://jira.tools.tax.service.gov.uk/browse/HMA-4482
* Added `isScreenReaderEnabled()` extension for `Context` in `ContextExt.kt`
* Added `dpToPx()` extension for `Float` in `FloatExtensions.kt`
* Improved announcement of errors for `TextInputView`
> HMA-4482: TextInputView errors

- README.md
- components-test/build.gradle
Update readme with release steps for the test library.
Increase the version number to account for the changes in https://github.com/hmrc/android-components/pull/49
> Component test library release 1.2.0

- CHANGELOG.md
- components/src/main/res/values/colors.xml
https://jira.tools.tax.service.gov.uk/browse/HMA-4618
Run sample to see example UI elements with the updated grey_1 colour
> HMA-4618 Updated grey 1

- components-compose/src/main/java/uk/gov/hmrc/components/compose/atom/bullet/BulletedTextView.kt
- components-compose/src/main/java/uk/gov/hmrc/components/compose/ui/theme/HmrcTypography.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/TextScreen.kt
> HMA-5067: Compose BulletedTextView

- CHANGELOG.md
- components/src/main/java/uk/gov/hmrc/components/organism/editable/EditableListItemViewState.kt
- components/src/main/java/uk/gov/hmrc/components/organism/editable/EditableListView.kt
- components/src/main/java/uk/gov/hmrc/components/organism/editable/EditableListViewAdapter.kt
- sample/src/main/java/uk/gov/hmrc/components/sample/organisms/EditableListViewFragment.kt
- sample/src/main/res/values/strings.xml
Fixed TalkBack accessibility bugs
Github Issue
- [x ] Updated CHANGELOG
Fixed bugs 5 and 6 on HMA-6086 with EditableListView
> TalkBack Accessibility Fixes

- CHANGELOG.md
- components/src/main/java/uk/gov/hmrc/components/organism/editable/EditableListViewAdapter.kt
Fixed action button visibility issues on EditableListView.
Test that current functionality of EditableListView remains unchanged - bug on build version of app.
> HMA-6727 action button visibility fixes

- CHANGELOG.md
- components/src/main/java/uk/gov/hmrc/components/organism/editable/EditableListViewAdapter.kt
- components/src/main/res/layout/editable_list_items.xml
- components/src/main/res/xml/scene_editing_mode.xml
Action button visibility changes made
> HMA 6727 change link visibility

- components-compose/src/main/java/uk/gov/hmrc/components/compose/molecule/item/SwitchRowView.kt
- components-compose/src/main/java/uk/gov/hmrc/components/compose/ui/theme/Theme.kt
- sample-compose-fragments/build.gradle.kts
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/data/repository/RepositoryImp.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/navigator/AppNavigator.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/navigator/Navigator.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/atoms/AtomsFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/atoms/ButtonFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/atoms/TextFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/colors/ColorsFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/molecules/BoldTitleBodyViewFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/molecules/H4TitleBodyViewFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/molecules/H5TitleBodyViewFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/molecules/InsetTextViewFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/molecules/InsetViewFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/molecules/MoleculesFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/molecules/MultiColumnRowViewFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/molecules/SwitchRowViewFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/SwitchRowViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/viewModel/SwitchRowViewModel.kt
- sample-compose-fragments/src/main/res/navigation/nav_graph_molecules.xml
- sample-compose-fragments/src/main/res/values/strings.xml
Adds the Material 3 SwitchRowView component built in Compose, with example usage in the sample-compose-fragments sample project.
> HMA-5075: Compose SwitchRowView

- CHANGELOG.md
- components/src/main/java/uk/gov/hmrc/components/molecule/status/StatusView.kt
- components/src/main/java/uk/gov/hmrc/components/molecule/titleBodyView/TitleBodyView.kt
- components/src/main/java/uk/gov/hmrc/components/organism/primary/PrimaryCardView.kt
- components/src/main/res/values/attrs.xml
- sample/src/main/res/layout/fragment_h4.xml
- sample/src/main/res/layout/fragment_primary_card.xml
- sample/src/main/res/values/strings.xml
Title and body content descriptions added for title body views. Title content description added for primary card view.
- [ x ] Updated CHANGELOG
Top example has the title and body content descriptions to test
N/A
> HMA-6828 Title and Body Content Descriptions

- CHANGELOG.md
> release note added in the CHANGELOG.md

- components-compose/src/main/java/uk/gov/hmrc/components/compose/atom/divider/HmrcDivider.kt
- components-compose/src/main/java/uk/gov/hmrc/components/compose/ui/theme/Dimensions.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/navigator/AppNavigator.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/navigator/Navigator.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/atoms/DividerFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/atoms/DividerScreen.kt
- sample-compose-fragments/src/main/res/navigation/nav_graph_atoms.xml
https://jira.tools.tax.service.gov.uk/browse/HMA-7520
> Divider atom added

- components-compose/src/main/java/uk/gov/hmrc/components/compose/organism/ComposableTemplate.kt
- components-compose/src/main/java/uk/gov/hmrc/components/compose/organism/card/IconButtonCardView.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/data/repository/RepositoryImp.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/domain/repository/Repository.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/navigator/AppNavigator.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/navigator/Navigator.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/molecules/MoleculesFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/organisms/IconButtonCardViewFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/ComponentListScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/colors/ColorsListScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/BoldTitleBodyViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/CurrencyInputViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/H4TitleBodyViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/H5TitleBodyViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/InsetTextViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/InsetViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/MultiColumnRowViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/SelectRowViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/StatusViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/SwitchRowViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/TextInputViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/WarningViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/organisms/IconButtonCardViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/sampletemplate/ComposableTemplate.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/viewModel/OrganismsViewModel.kt
- sample-compose-fragments/src/main/res/drawable/ic_help_outline.xml
- sample-compose-fragments/src/main/res/navigation/nav_graph.xml
Github Issue
https://jira.tools.tax.service.gov.uk/browse/HMA-5085
> HMA-5085: Compose for IconButtonCardView component

- buildSrc/src/main/java/uk/gov/hmrc/components/buildsrc/ComposeDependencies.kt
- components-compose/src/main/java/uk/gov/hmrc/components/compose/molecule/tabbar/TabBarView.kt
- components-compose/src/main/java/uk/gov/hmrc/components/compose/ui/theme/HmrcTypography.kt
- sample-compose-fragments/build.gradle.kts
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/data/repository/RepositoryImp.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/navigator/AppNavigator.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/navigator/Navigator.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/molecules/MoleculesFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/molecules/TabBarViewFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/TabBarViewScreen.kt
- sample-compose-fragments/src/main/res/navigation/nav_graph_molecules.xml
- sample-compose-fragments/src/main/res/values/strings.xml
Github Issue
https://jira.tools.tax.service.gov.uk/browse/HMA-5080
- Test Compose's TabBarView component behaves the same as the existing one.
> HMA-5085: Compose for TabBarView component

- components-compose/src/main/java/uk/gov/hmrc/components/compose/organism/container/SeparatedViewContainer.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/data/repository/RepositoryImp.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/navigator/AppNavigator.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/navigator/Navigator.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/organisms/OrganismsFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/organisms/SeparateViewContainerFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/organisms/SeparatedViewContainerFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/organisms/SeparatedViewContainerScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/sampletemplate/ComposableTemplate.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/viewModel/SeparatedViewContainerViewModel.kt
- sample-compose-fragments/src/main/res/navigation/nav_graph.xml
https://jira.tools.tax.service.gov.uk/browse/HMA-5070
> Separated View Container Fragment, Screen, View, View model added

- components-compose/src/main/java/uk/gov/hmrc/components/compose/molecule/input/CurrencyInputView.kt
- components-compose/src/main/java/uk/gov/hmrc/components/compose/molecule/input/TextInputView.kt
- components-compose/src/main/java/uk/gov/hmrc/components/compose/ui/theme/Theme.kt
- components-compose/src/main/res/values/strings.xml
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/CurrencyInputViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/TextInputViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/viewModel/CurrencyInputViewModel.kt
- sample-compose-fragments/src/main/res/values/strings.xml
Update compose versions of TextInputView and CurrencyInputView to new designs
> HMA-8140: text input view updates

- components-compose/CHANGELOG.md
- components-compose/src/main/java/uk/gov/hmrc/components/compose/molecule/selectrow/SelectRowView.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/molecules/SelectRowViewFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/BottomSheetViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/SelectRowViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/viewModel/SelectRowViewModel.kt
> HMA-8638: select row view improvement

- components/CHANGELOG.md
- components/src/main/java/uk/gov/hmrc/components/extensions/ViewExt.kt
- components/src/main/java/uk/gov/hmrc/components/organism/summary/SummaryRowView.kt
- components/src/main/res/values/strings.xml
- sample/src/main/java/uk/gov/hmrc/components/sample/organisms/SummaryRowFragment.kt
Github Issue
Second example on SummaryRowVIew content description updated
> HMA-7136 ViewExt

- components-compose/CHANGELOG.md
- components-compose/src/main/java/uk/gov/hmrc/components/compose/molecule/donut/DonutChartView.kt
- components-compose/src/main/java/uk/gov/hmrc/components/compose/ui/theme/Color.kt
- components-compose/src/main/java/uk/gov/hmrc/components/compose/ui/theme/Theme.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/data/repository/RepositoryImp.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/navigator/AppNavigator.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/navigator/Navigator.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/molecules/DonutChartViewFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/fragment/molecules/MoleculesFragment.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/DonutChartViewScreen.kt
- sample-compose-fragments/src/main/res/navigation/nav_graph_molecules.xml
- sample-compose-fragments/src/main/res/values/strings.xml
> HMA-7085: Compose DonutChartView

- components-compose/CHANGELOG.md
- components-compose/src/main/java/uk/gov/hmrc/components/compose/ui/theme/HmrcTypography.kt
- components-compose/src/main/java/uk/gov/hmrc/components/compose/ui/theme/Theme.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/atoms/TextScreen.kt
- sample-compose-fragments/src/main/res/values/strings.xml
> Compose Link text

- components-compose/CHANGELOG.md
- components-compose/src/main/java/uk/gov/hmrc/components/compose/atom/divider/HmrcDivider.kt
- components-compose/src/main/java/uk/gov/hmrc/components/compose/organism/container/SeparatedViewContainer.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/organisms/SeparatedViewContainerScreen.kt
> Enable setting of SeparatedViewContainer divider padding

- components-compose/CHANGELOG.md
- components-compose/src/main/java/uk/gov/hmrc/components/compose/molecule/bottomsheet/BottomSheetView.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/BottomSheetViewScreen.kt
- sample-compose-fragments/src/main/res/values/strings.xml
> Compose BottomSheet improvements

- components/CHANGELOG.md
- components/src/main/java/uk/gov/hmrc/components/organism/information/InformationMessageCardView.kt
- components/src/main/res/values/strings.xml
> HMA-8401 content descriptions

- components-compose/CHANGELOG.md
- components-compose/src/main/java/uk/gov/hmrc/components/compose/molecule/tabbar/TabBarView.kt
> Fix TabBarView unselected content dark mode colors

- components-compose/CHANGELOG.md
- components-compose/src/main/java/uk/gov/hmrc/components/compose/molecule/input/CurrencyInputView.kt
- components-compose/src/main/java/uk/gov/hmrc/components/compose/molecule/input/TextInputView.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/CurrencyInputViewScreen.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/molecules/TextInputViewScreen.kt
- sample-compose-fragments/src/main/res/values/strings.xml
> TextInputView/CurrencyInputView maxChars

- components-compose/CHANGELOG.md
- components-compose/src/main/java/uk/gov/hmrc/components/compose/molecule/input/TextInputView.kt
> Bugfix: TextInputView unfiltered input

- components-compose/CHANGELOG.md
- components-compose/src/main/java/uk/gov/hmrc/components/compose/atom/bullet/BulletedTextView.kt
- components-compose/src/main/res/values/strings.xml
> HMA-9039 Bulleted Point content description added

- components-compose/CHANGELOG.md
- components-compose/src/main/java/uk/gov/hmrc/components/compose/organism/primary/PrimaryCardView.kt
- sample-compose-fragments/src/main/java/uk/gov/hmrc/sample_compose_fragments/presentation/screens/organisms/PrimaryCardViewScreen.kt
> Update primary card view parameters

- components-compose/src/main/java/uk/gov/hmrc/components/compose/organism/summaryrow/SummaryRowView.kt
Github Issue
HMA-9537 Pega Child benefit page - Compose UI component update (Android)
> HMA-9537 Compose UI Component changes - PEGA

- components-compose/CHANGELOG.md
> HMA-9537 - Updated the component with link text style

- components-compose/CHANGELOG.md
> HMA-9567 removed line , added by mistake

- components-compose/src/main/java/uk/gov/hmrc/components/compose/molecule/input/CurrencyInputView.kt
Github Issue
https://github.com/hmrc/android-components/issues/HMA-9778
> HMA-9778-textview-accessibility-invalid-input
